Softversko2.EStore/Softversko2.EStore.Web/Models/Categories/CategoryViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace Softversko2.EStore.Web.Models.Categories
{
    public class CategoryViewModel
    {
        public int CategoryId { get; set; }
        [Required(ErrorMessage = "Ime kategorije opreme mora biti uneto")]
        [StringLength(50, ErrorMessage = "Ime mora biti manje od 50 karaktera")]
        public string Name { get; set; }
    }
}

Softversko2.EStore/Softversko2.EStore.Web/Areas/Administrations/Controllers/CategoryController.cs
using Softversko2.EStore.AppService.Abstractions.Categories;
using Softversko2.EStore.AppService.Messages.Categories;
using Softversko2.EStore.Web.Areas.Administrations.Models;
using Softversko2.EStore.Web.Mappings.Categories;
using Softversko2.EStore.Web.Models.Categories;
using System.Linq;
using System.Web.Mvc;

namespace Softversko2.EStore.Web.Areas.Administrations.Controllers
{
    [Authorize]
    public class CategoryController : Controller
    {
        private ICategoryService categoryService;

        public CategoryController(ICategoryService categoryService)
        {
            this.categoryService = categoryService;
        }

        public ActionResult Index()
        {
            CategoryListPageViewModel model = new CategoryListPageViewModel();
            FindAllCategoriesResponse response = categoryService.FindAllCategories();
            if (response.Success)
            {
                model.CategoryViewModels = response.Categories.ConvertToCategoryViewModelList();
                model.Success = true;
            }
            else
            {
                model.Success = false;
                model.ErrorMessage = response.Message;
            }

            return View(model);
        }

        public ActionResult Create()
        {
            CategorySinglePageViewModel model = new CategorySinglePageViewModel();
            model.CategoryViewModel = new CategoryViewModel();
            model.Success = true;
            return View("Edit", model);
        }

        public ActionResult Edit(int categoryId)
        {
            CategorySinglePageViewModel model = new CategorySinglePageViewModel();
            FindAllCategoriesResponse response = categoryService.FindAllCategories();
            if (response.Success)
            {
                model.CategoryViewModel = response.Categories.
                    Where(x => x.CategoryId == categoryId).
                    FirstOrDefault().
                    ConvertToCategoryViewModel();
                model.Success = true;
            }
            else
            {
                model.Success = false;
                model.ErrorMessage = response.Message;
            }
            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(CategorySinglePageViewModel model)
        {
            if (model.CategoryViewModel.CategoryId == 0)
            {
                CreateCategoryRequest request = new CreateCategoryRequest();
                CreateCategoryResponse response = new CreateCategoryResponse();
                request.Name = model.CategoryViewModel.Name;
                response = categoryService.CreateCategory(request);
                if (response.Success)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    model.Success = false;
                    model.ErrorMessage = response.Message;
                    return View(model);
                }
            }
            else
            {
                UpdateCategoryRequest request = new UpdateCategoryRequest();
                UpdateCategoryResponse response = new UpdateCategoryResponse();
                request.CategoryId = model.CategoryViewModel.CategoryId;
                request.Name = model.CategoryViewModel.Name;
                response = categoryService.UpdateCategory(request);
                if (response.Success)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    model.Success = false;
                    model.ErrorMessage = response.Message;
                    return View(model);
                }
            }
        }

        public ActionResult Delete(int categoryId)
        {
            DeleteCategoryRequest request = new DeleteCategoryRequest();
            DeleteCategoryResponse response = new DeleteCategoryResponse();
            request.CategoryId = categoryId;
            response = categoryService.DeleteCategory(request);
            if (response.Success)
            {
                return RedirectToAction("Index");
            }
            else
            {
                CategoryListPageViewModel model = new CategoryListPageViewModel();
                model.Success = false;
                model.ErrorMessage = response.Message;
                return View("Index", model);
            }
        }
    }
}

Softversko2.EStore/Softversko2.EStore.Web/Areas/Administrations/Views/Category/Edit.cshtml
@model Softversko2.EStore.Web.Areas.Administrations.Models.CategorySinglePageViewModel

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Kreiranje/izmena podataka o Tipu sata</h2>
<hr />

@if (Model.Success)
{
    using (Html.BeginForm("Edit", "Category", null, FormMethod.Post, new { @class = "form-horizontal" }))
    {
        @Html.HiddenFor(x => x.CategoryViewModel.CategoryId)
        <div class="form-group">
            <label class="control-label col-md-2">Ime tipa sata:</label>
            <div class="col-md-10">
                @Html.TextBoxFor(x => x.CategoryViewModel.Name, new { @class = "form-control" })
                @Html.ValidationMessage("CategoryViewModel.Name")
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <input class="btn btn-default" type="submit" value="Potvrdi" />
            </div>
        </div>
    }
}
else
{
    <div class="row">
        <div class="col-md-12">
            <div class="alert alert-danger">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                <strong>Greška!</strong> @Model.ErrorMessage
            </div>
        </div>
    </div>
}

Softversko2.EStore/Softversko2.EStore.Web/Areas/Administrations/Views/Category/Index.cshtml
@model Softversko2.EStore.Web.Areas.Administrations.Models.CategoryListPageViewModel

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Podaci o kategorijama opreme</h2>
<hr />

@if (Model.Success)
{
    @Html.RouteLink("Kreiraj novu",
        new
        {
            action = "Create",
            controller = "Category",
            area = "Administrations"
        },
        new { @class = "btn btn-default" }
    )
    <table class="table table-bordred table-striped">
        <thead>
            <tr>
                <th>Ime kategorije opreme</th>
                <th></th>
            </tr>
        </thead>

        <tbody>
            @foreach (var category in Model.CategoryViewModels)
            {
                <tr>
                    <td>@category.Name</td>
                    <td>
                        <a href="@Url.Action("Edit", "Category", new { categoryId = category.CategoryId })" class="btn btn-primary-table btn-xs"><span class="glyphicon glyphicon-pencil"></span></a>
                        <a href="@Url.Action("Delete", "Category", new { categoryId = category.CategoryId })" class="btn btn-primary-table btn-xs" onclick="return confirm('Da li ste sigurni da želite da obrišete dati tip sata?')"><span class="glyphicon glyphicon-trash"></span></a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <div class="row">
        <div class="col-md-12">
            <div class="alert alert-danger">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                <strong>Greška!</strong> @Model.ErrorMessage
            </div>
        </div>
    </div>
}