Softversko2.EStore/Softversko2.EStore.Web/Areas/Administrations/Controllers/BrandController.cs
using Softversko2.EStore.AppService.Abstractions.Brands;
using Softversko2.EStore.AppService.Messages.Brands;
using Softversko2.EStore.Web.Areas.Administrations.Models;
using System.Linq;
using System.Web.Mvc;
using Softversko2.EStore.Web.Mappings.Brands;
using Softversko2.EStore.Web.Models.Brands;

namespace Softversko2.EStore.Web.Areas.Administrations.Controllers
{
    [Authorize]
    public class BrandController : Controller
    {
        private IBrandService brandService;

        public BrandController(IBrandService brandService)
        {
            this.brandService = brandService;
        }

        public ActionResult Index()
        {
            BrandListPageViewModel model = new BrandListPageViewModel();
            FindAllBrandsResponse response = brandService.FindAllBrands();
            if (response.Success)
            {
                model.BrandViewModels = response.Brands.ConvertToBrandViewModelList();
                model.Success = true;
            }
            else
            {
                model.Success = false;
                model.ErrorMessage = response.Message;
            }

            return View(model);
        }

        public ActionResult Create()
        {
            BrandSinglePageViewModel model = new BrandSinglePageViewModel();
            model.BrandViewModel = new BrandViewModel();
            model.Success = true;
            return View("Edit", model);
        }

        public ActionResult Edit(int brandId)
        {
            BrandSinglePageViewModel model = new BrandSinglePageViewModel();
            FindAllBrandsResponse response = brandService.FindAllBrands();
            if (response.Success)
            {
                model.BrandViewModel = response.Brands.
                    Where(x => x.BrandId == brandId).
                    FirstOrDefault().
                    ConvertToBrandViewModel();
                model.Success = true;
            }
            else
            {
                model.Success = false;
                model.ErrorMessage = response.Message;
            }
            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(BrandSinglePageViewModel model)
        {
            if (model.BrandViewModel.BrandId == 0)
            {
                CreateBrandRequest request = new CreateBrandRequest();
                CreateBrandResponse response = new CreateBrandResponse();
                request.Name = model.BrandViewModel.Name;
                response = brandService.CreateBrand(request);
                if (response.Success)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    model.Success = false;
                    model.ErrorMessage = response.Message;
                    return View(model);
                }
            }
            else
            {
                UpdateBrandRequest request = new UpdateBrandRequest();
                UpdateBrandResponse response = new UpdateBrandResponse();
                request.BrandId = model.BrandViewModel.BrandId;
                request.Name = model.BrandViewModel.Name;
                response = brandService.UpdateBrand(request);
                if (response.Success)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    model.Success = false;
                    model.ErrorMessage = response.Message;
                    return View(model);
                }
            }
        }

        public ActionResult Delete(int brandId)
        {
            DeleteBrandRequest request = new DeleteBrandRequest();
            DeleteBrandResponse response = new DeleteBrandResponse();
            request.BrandId = brandId;
            response = brandService.DeleteBrand(request);
            if (response.Success)
            {
                return RedirectToAction("Index");
            }
            else
            {
                BrandListPageViewModel model = new BrandListPageViewModel();
                model.Success = false;
                model.ErrorMessage = response.Message;
                return View("Index", model);
            }
        }
    }
}

Softversko2.EStore/Softversko2.EStore.Web/Areas/Administrations/Controllers/UserController.cs
using Softversko2.EStore.AppService.Abstractions.Users;
using Softversko2.EStore.AppService.Messages.Users;
using Softversko2.EStore.Web.Areas.Administrations.Models;
using Softversko2.EStore.Web.Mappings.Users;
using Softversko2.EStore.Web.Models.Users;
using System;
using System.Linq;
using System.Web.Mvc;

namespace Softversko2.EStore.Web.Areas.Administrations.Controllers
{
    [Authorize]
    public class UserController : Controller
    {
        private IUserService userService;

        public UserController(IUserService userService)
        {
            this.userService = userService;
        }

        public ActionResult Index()
        {
            UserListPageViewModel model = new UserListPageViewModel();
            FindAllUsersResponse response = userService.ReadUsers();
            if (response.Success)
            {
                model.UserViewModels = response.Users.ConvertToUserViewModelList();
                model.Success = true;
            }
            else
            {
                model.Success = false;
                model.ErrorMessage = response.Message;
            }

            return View(model);
        }

        public ActionResult Create()
        {
            UserSinglePageViewModel model = new UserSinglePageViewModel();
            model.UserViewModel = new UserViewModel();
            model.Success = true;
            return View("Edit", model);
        }

        public ActionResult Edit(Guid userId)
        {
            UserSinglePageViewModel model = new UserSinglePageViewModel();
            FindAllUsersResponse response = userService.ReadUsers();
            if (response.Success)
            {
                model.UserViewModel = response.Users.
                    Where(x => x.UserId == userId).
                    FirstOrDefault().
                    ConvertToUserViewModel();
                model.Success = true;
            }
            else
            {
                model.Success = false;
                model.ErrorMessage = response.Message;
            }
            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(UserSinglePageViewModel model)
        {
            if (model.UserViewModel.UserId.Equals(Guid.Empty))
            {
                CreateUserRequest request = new CreateUserRequest();
                CreateUserResponse response = new CreateUserResponse();
                request.UserId = Guid.NewGuid();
                request.Username = model.UserViewModel.Username;
                request.Password = model.UserViewModel.Password;
                request.Email = model.UserViewModel.Email;
                request.Role = model.UserViewModel.Role.ToString();

                response = userService.CreateUser(request);
                if (response.Success)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    model.Success = false;
                    model.ErrorMessage = response.Message;
                    return View(model);
                }
            }
            else
            {
                UpdateUserRequest request = new UpdateUserRequest();
                UpdateUserResponse response = new UpdateUserResponse();
                request.UserId = model.UserViewModel.UserId;
                request.Username = model.UserViewModel.Username;
                request.Password = model.UserViewModel.Password;
                request.Email = model.UserViewModel.Email;
                request.Role = model.UserViewModel.Role.ToString();

                response = userService.UpdateUser(request);
                if (response.Success)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    model.Success = false;
                    model.ErrorMessage = response.Message;
                    return View(model);
                }
            }
        }

        public ActionResult Delete(Guid userId)
        {
            DeleteUserRequest request = new DeleteUserRequest();
            DeleteUserResponse response = new DeleteUserResponse();
            request.UserId = userId;
            response = userService.DeleteUser(request);
            if (response.Success)
            {
                return RedirectToAction("Index");
            }
            else
            {
                ProductListPageViewModel model = new ProductListPageViewModel();
                model.Success = false;
                model.ErrorMessage = response.Message;
                return View("Index", model);
            }
        }
    }
}

Softversko2.EStore/Softversko2.EStore.Web/Areas/Products/Controllers/CartController.cs
using Softversko2.EStore.Model.Entities.Carts;
using Softversko2.EStore.Model.Entities.Orders;
using Softversko2.EStore.Model.Entities.Products;
using Softversko2.EStore.Model.Entities.Shipping;
using Softversko2.EStore.Web.Areas.Products.Models;
using System.Linq;
using System.Web.Mvc;

namespace Softversko2.EStore.Web.Areas.Products.Controllers
{
    public class CartController : Controller
    {
        private IProductRepository repository;

        public CartController(IProductRepository repo)
        {
            repository = repo;
        }

        public ViewResult Index(string returnUrl)
        {
            return View(new CartPageViewModel
            {
                Cart = GetCart(),
                ReturnUrl = returnUrl
            });
        }

        public RedirectToRouteResult AddToCart(int productId, string returnUrl)
        {
            Product product = repository.ReadAll()
                .FirstOrDefault(p => p.ProductId == productId);
            if (product != null)
            {
                GetCart().AddItem(product, 1);
            }
            return RedirectToAction("Index", new { returnUrl });
        }

        public RedirectToRouteResult RemoveFromCart(int productId, string returnUrl)
        {
            Product product = repository.ReadAll()
                .FirstOrDefault(p => p.ProductId == productId);
            if (product != null)
            {
                GetCart().RemoveLine(product);
            }
            return RedirectToAction("Index", new { returnUrl });
        }

        public ViewResult ShippingAddress()
        {
            return View(new ShippingDetails());
        }

        [HttpPost]
        public ViewResult ShippingAddress(ShippingDetails model)
        {
            Order order = (Order)Session["Order"];
            order.ShippingDetails = model;
            return View("DeliveryOperator");
        }

        public ViewResult DeliveryOperator()
        {
            return View();
        }

        [HttpPost]
        public ViewResult DeliveryOperator(string operatorName)
        {
            Order order = (Order)Session["Order"];
            order.DeliveryOperator = DeliveryFactory.CreateDeliveryOperator(operatorName);
            return View("DiscountSelection");
        }

        public ViewResult DiscountSelection()
        {
            return View();
        }

        [HttpPost]
        public ViewResult DiscountSelection(string discountCode)
        {
            if (discountCode == "mojsat")
            {
                Order order = (Order)Session["Order"];
                order.Cart.SetCartDiscountStrategy("MoneyOff");
            }
            return View("OrderSummary", (Order)Session["Order"]);
        }

        private Cart GetCart()
        {
            Order order = (Order)Session["Order"];

            if (order == null)
            {
                order = new Order();
                order.Cart = new Cart();
                Session["Order"] = order;
            }
            return order.Cart;
        }
    }
}

Softversko2.EStore/Softversko2.EStore.Web/Areas/Products/Controllers/ProductController.cs
using Softversko2.EStore.AppService.Abstractions.Products;
using Softversko2.EStore.AppService.Messages.Products;
using Softversko2.EStore.Web.Areas.Products.Models;
using Softversko2.EStore.Web.Mappings.Products;
using Softversko2.EStore.Web.Models.Products;
using System.Web.Mvc;

namespace Softversko2.EStore.Web.Areas.Products.Controllers
{
public class ProductController : Controller
    {
private IProductService productService;

    public ProductController(IProductService productService)
    {
        this.productService = productService;
    }

    // GET: Products/Product
    public ActionResult Index()
    {
        FindAllProductsResponse response = new FindAllProductsResponse();
        response = productService.FindAllProducts();

        AllProductsPageViewModel model = new AllProductsPageViewModel();
        model.ProductViewModels = response.Products.ConvertToProductViewModelList();
        model.Success = response.Success;
        model.ErrorMessage = response.Message;

        return View(model);
    }

    public FileContentResult GetImage(int productId)
    {
        ProductViewModel productViewModel = productService.FindAllProducts().Products.
                        Find(x => x.ProductId == productId).ConvertToProductViewModel();
        if (productViewModel != null)
        {
            return File(productViewModel.ProductImageViewModel.ImageData, productViewModel.ProductImageViewModel.ImageMimeType);
        }
        else
        {
            return null;
        }
    }
}
}

Softversko2.EStore/Softversko2.EStore.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title -Prodavnica satova</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>

    <div class="container">
        <div id="myCarousel" class="carousel slide" data-ride="carousel">
            <!-- Indicators -->
            <ol class="carousel-indicators">
                <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                <li data-target="#myCarousel" data-slide-to="1"></li>
                <li data-target="#myCarousel" data-slide-to="2"></li>

            </ol>

            <!-- Wrapper for slides -->
            <div class="carousel-inner" role="listbox">
                <div class="item active">
                    <img src="~/Content/images/slika11.png" width="1140" />
                    <div class="carousel-caption">
                        <h3>Tvoj zivot</h3>

                    </div>
                </div>
                <div class="item">
                    <img src="~/Content/images/slika12.png" width="1140" />
                    <div class="carousel-caption">
                        <h3>Tvoje vreme</h3>

                    </div>
                </div>
                <div class="item">
                    <img src="~/Content/images/slika13.png" width="1140" />
                    <div class="carousel-caption">
                        <h3>Ne traci ih</h3>
                    </div>
                </div>


            </div>
        </div>



        <nav class="navbar navbar-inverse">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("Satovi", "Index", "Product", new { area = "Products" }, new { @class = "navbar-brand" })
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li class="active">@Html.ActionLink("Početna", "Index", "Product", new { area = "Products" }, null)</li>
                        <li class="active">@Html.ActionLink("Korpa", "Index", "Cart", new { area = "Products" }, null)</li>
                        <li class="active">@Html.ActionLink("Delovi", "Index", "Delovi", new { area = "Products" }, null)</li>
                        @if (Request.IsAuthenticated && User.IsInRole("Administrator"))
                        {
                            <li class="dropdown">
                                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                    Administracija
                                    <span class="caret"></span>
                                </a>
                                <ul class="dropdown-menu">
                                    <li>@Html.ActionLink("Satovi", "Index", "Product", new { area = "Administrations" }, null)</li>
                                    <li>@Html.ActionLink("Marka", "Index", "Brand", new { area = "Administrations" }, null)</li>
                                    <li>@Html.ActionLink("Tip", "Index", "Category", new { area = "Administrations" }, null)</li>
                                    <li>@Html.ActionLink("Korisnici", "Index", "User", new { area = "Administrations" }, null)</li>
                                    <li>@Html.ActionLink("Delovi", "Index", "Delovi", new { area = "Administrations" }, null)</li>
                                </ul>
                            </li>
                        }
                    </ul>
                    @if (Request.IsAuthenticated)
                    {
                        <ul class="nav navbar-nav navbar-right">
                            <li><a href="/Account/Logout"><span class="glyphicon glyphicon-log-out"></span> Izloguj se</a></li>
                        </ul>
                    }
                    else
                    {
                        <ul class="nav navbar-nav navbar-right">
                            <li><a href="/Account/Register"><span class="glyphicon glyphicon-user"></span> Registruj se</a></li>
                            <li><a href="/Account/Login"><span class="glyphicon glyphicon-log-in"></span> Uloguj se</a></li>
                        </ul>
                    }
                </div>
            </div>
        </nav>

    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Satovi</p>





        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>