Softversko2.EStore/Softversko2.EStore.Web/Models/Delovi/DeoImageViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Softversko2.EStore.Web.Models.Delovi
{
    public class DeoImageViewModel
    {
        public byte[] ImageData { get; set; }
        public string ImageMimeType { get; set; }
    
}
}

Softversko2.EStore/Softversko2.EStore.Web/Models/Delovi/DeoViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Softversko2.EStore.Web.Models.Delovi
{
    public class DeoViewModel
    {
        public int DeoId { get; set; }
        public string Ime { get; set; }
        [Required(ErrorMessage = "Ime  mora biti unet")]
        public string Opis { get; set; }
        [Required(ErrorMessage = "Opis  mora biti uneta")]
        public string Cena { get; set; }
        [Required(ErrorMessage = "Cena  mora biti uneta")]
        public string Velicina { get; set; }
        [Required(ErrorMessage = "Veličina mora biti unet")]
        public int BrandId { get; set; }
        public string BrandName { get; set; }
        [Required(ErrorMessage = "Marka opreme mora biti uneta")]

        public DeoImageViewModel DeoImageViewModel { get; set; }
        public List<DeoImageViewModel> DeoImageViewModels { get; set; }
    }
}

Softversko2.EStore/Softversko2.EStore.Web/Areas/Administrations/Controllers/DeloviController.cs
using Softversko2.EStore.AppService.Abstractions.Brands;
using Softversko2.EStore.AppService.Abstractions.Delovi;
using Softversko2.EStore.AppService.Messages.Delovi;
using Softversko2.EStore.Model.Entities.Delovi;
using Softversko2.EStore.Web.Areas.Administrations.Models;
using Softversko2.EStore.Web.Mappings.Brands;
using Softversko2.EStore.Web.Mappings.Delovi;
using Softversko2.EStore.Web.Models.Delovi;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Softversko2.EStore.Web.Areas.Administrations.Controllers
{
    [Authorize]
    public class DeloviController : Controller
    {
        private IDeoService deoService;
        private IBrandService brandService;
     

        public DeloviController(IDeoService deoService,
            IBrandService brandService)
        {
            this.deoService = deoService;
            this.brandService = brandService;
          
        }

        public ActionResult Index()
        {
            DeloviListPageViewModel model = new DeloviListPageViewModel();
            FindAllDeloviResponse response = deoService.FindAllDelovi();
            if (response.Success)
            {
                model.DeoViewModels = response.Delovi.ConvertToDeoViewModelList();
                model.Success = true;
            }
            else
            {
                model.Success = false;
                model.ErrorMessage = response.Message;
            }

            return View(model);
        }

        public ActionResult Create()
        {
            DeloviSinglePageViewModel model = new DeloviSinglePageViewModel();
            model.DeoViewModel = new DeoViewModel();
            model.BrandViewModels = brandService.FindAllBrands().Brands.ConvertToBrandViewModelList();
            return View("Edit", model);
        }

        public ActionResult Edit(int deoId)
        {
            DeloviSinglePageViewModel model = new DeloviSinglePageViewModel();
            FindAllDeloviResponse response = deoService.FindAllDelovi();
            if (response.Success)
            {
                model.DeoViewModel = response.Delovi.
                    Where(x => x.DeoId == deoId).
                    FirstOrDefault().
                    ConvertToDeoViewModel();
                model.BrandViewModels = brandService.FindAllBrands().Brands.ConvertToBrandViewModelList();
                model.Success = true;
            }
            else
            {
                model.Success = false;
                model.ErrorMessage = response.Message;
            }
            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(DeloviSinglePageViewModel model, List<HttpPostedFileBase> fileUpload)
        {
            if (model.DeoViewModel.DeoId == 0)
            {
                CreateDeloviRequest request = new CreateDeloviRequest();
                CreateDeloviResponse response = new CreateDeloviResponse();
                request.Ime= model.DeoViewModel.Ime;
                request.Opis = model.DeoViewModel.Opis;
                request.Cena = model.DeoViewModel.Cena;
                request.Velicina = model.DeoViewModel.Velicina;
                request.BrandId = model.DeoViewModel.BrandId;
                request.DeoImages = new List<DeoImage>();

                foreach (HttpPostedFileBase image in fileUpload)
                {
                    if (image != null)
                    {
                        DeoImage deoImeage = new DeoImage();
                        deoImeage.ImageMimeType = image.ContentType;
                        deoImeage.ImageData = new byte[image.ContentLength];
                        image.InputStream.Read(deoImeage.ImageData, 0, image.ContentLength);
                        // First image add for displaying in product list page
                        if (request.DeoImage == null)
                        {
                            request.DeoImage = new DeoImage();
                            request.DeoImage = deoImeage;
                        }
                        // Other images add to list
                        request.DeoImages.Add(deoImeage);
                    }
                }

                response = deoService.CreateDeo(request);
                if (response.Success)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    model.Success = false;
                    model.ErrorMessage = response.Message;
                    return View(model);
                }
            }
            else
            {
                UpdateDeloviRequest request = new UpdateDeloviRequest();
                UpdateDeloviResponse response = new UpdateDeloviResponse();
                request.DeoId = model.DeoViewModel.DeoId;
                request.Ime = model.DeoViewModel.Ime;
                request.Opis = model.DeoViewModel.Opis;
                request.Cena = model.DeoViewModel.Cena;
                request.Velicina = model.DeoViewModel.Velicina;
                request.BrandId = model.DeoViewModel.BrandId;
                request.DeoImages = new List<DeoImage>();

                foreach (HttpPostedFileBase image in fileUpload)
                {
                    if (image != null)
                    {
                        DeoImage deoImeage = new DeoImage();
                        deoImeage.ImageMimeType = image.ContentType;
                        deoImeage.ImageData = new byte[image.ContentLength];
                        image.InputStream.Read(deoImeage.ImageData, 0, image.ContentLength);
                        // First image add for displaying in product list page
                        if (request.DeoImage == null)
                        {
                            request.DeoImage = new DeoImage();
                            request.DeoImage = deoImeage;
                        }
                        // Other images add to list
                        request.DeoImages.Add(deoImeage);
                    }
                }
                response = deoService.UpdateDeo(request);
                if (response.Success)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    model.Success = false;
                    model.ErrorMessage = response.Message;
                    return View(model);
                }
            }
        }

        public ActionResult Delete(int DeoId)
        {
            DeleteDeloviRequest request = new DeleteDeloviRequest();
            DeleteDeloviResponse response = new DeleteDeloviResponse();
            request.DeoId = DeoId;
            response = deoService.DeleteDeo(request);
            if (response.Success)
            {
                return RedirectToAction("Index");
            }
            else
            {
               DeloviListPageViewModel model = new DeloviListPageViewModel();
                model.Success = false;
                model.ErrorMessage = response.Message;
                return View("Index", model);
            }
        }
    }
}

Softversko2.EStore/Softversko2.EStore.Web/Areas/Products/Controllers/DeloviController.cs
using Softversko2.EStore.AppService.Abstractions.Delovi;
using Softversko2.EStore.AppService.Implementations.Delovi;
using Softversko2.EStore.AppService.Messages.Delovi;
using Softversko2.EStore.Web.Areas.Products.Models;
using Softversko2.EStore.Web.Mappings.Delovi;
using Softversko2.EStore.Web.Models.Delovi;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Softversko2.EStore.Web.Areas.Products.Controllers
{
    public class DeloviController : Controller
    { 
   private IDeoService deoService;

    public DeloviController(IDeoService deoService)
    {
        this.deoService = deoService;
    }

    // GET: Products/Product
    public ActionResult Index()
    {
        FindAllDeloviResponse response = new FindAllDeloviResponse();
        response = deoService.FindAllDelovi();

        AllDeloviPageViewModel model = new AllDeloviPageViewModel();
        model.DeoViewModels = response.Delovi.ConvertToDeoViewModelList();
        model.Success = response.Success;
        model.ErrorMessage = response.Message;

        return View(model);
    }

    public FileContentResult GetImage(int deoId)
    {
        DeoViewModel deoViewModel = deoService.FindAllDelovi().Delovi.
                        Find(x => x.DeoId == deoId).ConvertToDeoViewModel();
        if (deoViewModel != null)
        {
            return File(deoViewModel.DeoImageViewModel.ImageData, deoViewModel.DeoImageViewModel.ImageMimeType);
        }
        else
        {
            return null;
        }
    }
}
}

Softversko2.EStore/Softversko2.EStore.Web/Areas/Administrations/Views/Delovi/Edit.cshtml
@model Softversko2.EStore.Web.Areas.Administrations.Models.DeloviSinglePageViewModel

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Kreiranje/izmena podataka o Delu</h2>
<hr />

@if (Model.Success)
{
    using (Html.BeginForm("Edit", "Delovi", null, FormMethod.Post, new { @class = "form-horizontal", enctype = "multipart/form-data" }))
    {
        @Html.HiddenFor(x => x.DeoViewModel.DeoId)
        <div class="form-group">
            <label class="control-label col-md-2">Ime dela:</label>
            <div class="col-md-10">
                @Html.TextBoxFor(x => x.DeoViewModel.Ime, new { @class = "form-control" })
                @Html.ValidationMessage("DeoViewModel.Ime")
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-2">Opis:</label>
            <div class="col-md-10">
                @Html.TextAreaFor(x => x.DeoViewModel.Opis, new { @class = "form-control" })
                @Html.ValidationMessage("DeoViewModel.Description")
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-2">Cena:</label>
            <div class="col-md-10">
                @Html.TextBoxFor(x => x.DeoViewModel.Cena, new { @class = "form-control" })
                @Html.ValidationMessage("DeoViewModel.Cena")
            </div>
        </div>
       
        <div class="form-group">
            <label class="control-label col-md-2">Veličina:</label>
            <div class="col-md-10">
                @Html.TextBoxFor(x => x.DeoViewModel.Velicina, new { @class = "form-control" })
                @Html.ValidationMessage("DeoViewModel.Velicina")
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-2">Marka:</label>
            <div class="col-md-10">
                @Html.DropDownListFor(x => x.DeoViewModel.BrandId, new SelectList(Model.BrandViewModels, "BrandId", "Name"), new { @class = "form-control" })
                @Html.ValidationMessage("DeoViewModel.BrandId")
            </div>

        </div>
        <div class="form-group">
            <label class="control-label col-md-2">Slike:</label>
            <div class="col-md-10">
                <input type="file" id="fileToUpload" name="fileUpload" multiple="multiple" class="form-control" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <input class="btn btn-default" type="submit" value="Potvrdi" />
            </div>
        </div>
    }
}
else
{
    <div class="row">
        <div class="col-md-12">
            <div class="alert alert-danger">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                <strong>Greška!</strong> @Model.ErrorMessage
            </div>
        </div>
    </div>
}

Softversko2.EStore/Softversko2.EStore.Web/Areas/Administrations/Views/Delovi/Index.cshtml
@model Softversko2.EStore.Web.Areas.Administrations.Models.DeloviListPageViewModel

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2> Podaci o Delovima </h2>>
<hr />

@if (Model.Success)
{
    @Html.RouteLink("Kreiraj nov",
        new
        {
            action = "Create",
            controller = "Delovi",
            area = "Administrations"
        },
        new { @class = "btn btn-default" }
    )
    <table class="table table-bordred table-striped">
        <thead>
            <tr>
                <th>Ime dela</th>
                <th>Ime marke</th>
                <th></th>
            </tr>
        </thead>

        <tbody>
            @foreach (var deo in Model.DeoViewModels)
            {
                <tr>
                    <td>@deo.Ime</td>
                    <td>@deo.BrandName</td>
                    <td>
                        <a href="@Url.Action("Edit", "Delovi", new { deoId = deo.DeoId })" class="btn btn-primary-table btn-xs"><span class="glyphicon glyphicon-pencil"></span></a>
                        <a href="@Url.Action("Delete", "Delovi", new { deoId = deo.DeoId })" class="btn btn-primary-table btn-xs" onclick="return confirm('Da li ste sigurni da želite da obrišete dati deo?')"><span class="glyphicon glyphicon-trash"></span></a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <div class="row">
        <div class="col-md-12">
            <div class="alert alert-danger">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                <strong>Greška!</strong> @Model.ErrorMessage
            </div>
        </div>
    </div>
}